### ISSUE TITLE
ctrl

### ISSUE THREAD

**Issue by myungjaeyu** [u4bi/node-restify_restfulAPI-design#1]
고민고민 나누긴해야하는데

**Comment by myungjaeyu** [comment]
전 처럼 모든 로직을 다 나누는건 좀 비효율적인거 같고

**Comment by myungjaeyu** [comment]
한곳에 몰아넣자니 코드가 길어지고

**Comment by myungjaeyu** [comment]
지금 좀 고민중인게 모델 매니저단을 만들까 생각중 일단 자고 일어나면 결정되겠지

**Comment by u4bi** [comment]
굿 뺌

**Comment by u4bi** [comment]
var api = require('../service/send-JSON.js');

function create(req, res){
    var userInsert = require('../model/board/insert.js');
	api(res, userInsert(req));
}

function index(req, res){
    var userSelectAll = require('../model/board/selects.js');
    api(res, userSelectAll());
}

function show(req, res){
    var userSelect = require('../model/board/select.js');
    api(res, userSelect(req));
}

function update(req, res){
    var userUpdate = require('../model/board/update.js');
    api(res, userUpdate(req));
}
function destory(req, res){
    var userDelete = require('../model/board/delete.js');
    api(res, userDelete(req));
}

exports.create = create;
exports.index = index;
exports.show = show;
exports.update = update;
exports.destory = destory;

**Comment by u4bi** [comment]
##### ex 예 Insert 모델단)

    var async = require('async');
    function query(req){
    var data;
    async.waterfall([function(callback){
        callback(null, "1");
    },function(arg,callback){
        
        var p = req.params;
        var temp = { insert_sql : arg+' '+p.id};
        callback(null, temp);
        
    }],function(err, result){
        if(err) console.log(err);
        data = result;
    });
    return data;
    }

    module.exports = query;
